//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessSolution.BS_MasterDataService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PagerInfo", Namespace="http://schemas.datacontract.org/2004/07/BussinessSolutionServiceBLL")]
    [System.SerializableAttribute()]
    public partial class PagerInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FilterField;
        
        private int PageIndexField;
        
        private int PageSizeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filter {
            get {
                return this.FilterField;
            }
            set {
                if ((object.ReferenceEquals(this.FilterField, value) != true)) {
                    this.FilterField = value;
                    this.RaisePropertyChanged("Filter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int PageIndex {
            get {
                return this.PageIndexField;
            }
            set {
                if ((this.PageIndexField.Equals(value) != true)) {
                    this.PageIndexField = value;
                    this.RaisePropertyChanged("PageIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int PageSize {
            get {
                return this.PageSizeField;
            }
            set {
                if ((this.PageSizeField.Equals(value) != true)) {
                    this.PageSizeField = value;
                    this.RaisePropertyChanged("PageSize");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SupplierInfo", Namespace="http://schemas.datacontract.org/2004/07/BussinessSolutionServiceBLL")]
    [System.SerializableAttribute()]
    public partial class SupplierInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        private bool IsManufactureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PincodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        private long SupplierIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupplierNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TINField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool IsManufacture {
            get {
                return this.IsManufactureField;
            }
            set {
                if ((this.IsManufactureField.Equals(value) != true)) {
                    this.IsManufactureField = value;
                    this.RaisePropertyChanged("IsManufacture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pincode {
            get {
                return this.PincodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PincodeField, value) != true)) {
                    this.PincodeField = value;
                    this.RaisePropertyChanged("Pincode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long SupplierID {
            get {
                return this.SupplierIDField;
            }
            set {
                if ((this.SupplierIDField.Equals(value) != true)) {
                    this.SupplierIDField = value;
                    this.RaisePropertyChanged("SupplierID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupplierName {
            get {
                return this.SupplierNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplierNameField, value) != true)) {
                    this.SupplierNameField = value;
                    this.RaisePropertyChanged("SupplierName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TIN {
            get {
                return this.TINField;
            }
            set {
                if ((object.ReferenceEquals(this.TINField, value) != true)) {
                    this.TINField = value;
                    this.RaisePropertyChanged("TIN");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductInfo", Namespace="http://schemas.datacontract.org/2004/07/BussinessSolutionServiceBLL")]
    [System.SerializableAttribute()]
    public partial class ProductInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisplayProductNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char IsDifferentRateInSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char IsGiftItemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char IsTaxableItemField;
        
        private BussinessSolution.BS_MasterDataService.CategoryInfo ProductCategoryInfoField;
        
        private int ProductCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductDescriptionField;
        
        private decimal ProfitPrecentageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BussinessSolution.BS_MasterDataService.SupplierInfo VendorInfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayProductName {
            get {
                return this.DisplayProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayProductNameField, value) != true)) {
                    this.DisplayProductNameField = value;
                    this.RaisePropertyChanged("DisplayProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char IsDifferentRateInSize {
            get {
                return this.IsDifferentRateInSizeField;
            }
            set {
                if ((this.IsDifferentRateInSizeField.Equals(value) != true)) {
                    this.IsDifferentRateInSizeField = value;
                    this.RaisePropertyChanged("IsDifferentRateInSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char IsGiftItem {
            get {
                return this.IsGiftItemField;
            }
            set {
                if ((this.IsGiftItemField.Equals(value) != true)) {
                    this.IsGiftItemField = value;
                    this.RaisePropertyChanged("IsGiftItem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char IsTaxableItem {
            get {
                return this.IsTaxableItemField;
            }
            set {
                if ((this.IsTaxableItemField.Equals(value) != true)) {
                    this.IsTaxableItemField = value;
                    this.RaisePropertyChanged("IsTaxableItem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public BussinessSolution.BS_MasterDataService.CategoryInfo ProductCategoryInfo {
            get {
                return this.ProductCategoryInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductCategoryInfoField, value) != true)) {
                    this.ProductCategoryInfoField = value;
                    this.RaisePropertyChanged("ProductCategoryInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ProductCode {
            get {
                return this.ProductCodeField;
            }
            set {
                if ((this.ProductCodeField.Equals(value) != true)) {
                    this.ProductCodeField = value;
                    this.RaisePropertyChanged("ProductCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductDescription {
            get {
                return this.ProductDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductDescriptionField, value) != true)) {
                    this.ProductDescriptionField = value;
                    this.RaisePropertyChanged("ProductDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal ProfitPrecentage {
            get {
                return this.ProfitPrecentageField;
            }
            set {
                if ((this.ProfitPrecentageField.Equals(value) != true)) {
                    this.ProfitPrecentageField = value;
                    this.RaisePropertyChanged("ProfitPrecentage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BussinessSolution.BS_MasterDataService.SupplierInfo VendorInfo {
            get {
                return this.VendorInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.VendorInfoField, value) != true)) {
                    this.VendorInfoField = value;
                    this.RaisePropertyChanged("VendorInfo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CategoryInfo", Namespace="http://schemas.datacontract.org/2004/07/BussinessSolutionServiceBLL")]
    [System.SerializableAttribute()]
    public partial class CategoryInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CategoryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryCode {
            get {
                return this.CategoryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryCodeField, value) != true)) {
                    this.CategoryCodeField = value;
                    this.RaisePropertyChanged("CategoryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryID {
            get {
                return this.CategoryIDField;
            }
            set {
                if ((this.CategoryIDField.Equals(value) != true)) {
                    this.CategoryIDField = value;
                    this.RaisePropertyChanged("CategoryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryName {
            get {
                return this.CategoryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryNameField, value) != true)) {
                    this.CategoryNameField = value;
                    this.RaisePropertyChanged("CategoryName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BS_MasterDataService.IMasterDataService")]
    public interface IMasterDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterDataService/GetSupplierInfo", ReplyAction="http://tempuri.org/IMasterDataService/GetSupplierInfoResponse")]
        BussinessSolution.BS_MasterDataService.SupplierInfo[] GetSupplierInfo(BussinessSolution.BS_MasterDataService.PagerInfo pagerInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterDataService/GetSupplierInfo", ReplyAction="http://tempuri.org/IMasterDataService/GetSupplierInfoResponse")]
        System.Threading.Tasks.Task<BussinessSolution.BS_MasterDataService.SupplierInfo[]> GetSupplierInfoAsync(BussinessSolution.BS_MasterDataService.PagerInfo pagerInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterDataService/InsertOrUpdateSupplierInfo", ReplyAction="http://tempuri.org/IMasterDataService/InsertOrUpdateSupplierInfoResponse")]
        bool InsertOrUpdateSupplierInfo(BussinessSolution.BS_MasterDataService.SupplierInfo supplierInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterDataService/InsertOrUpdateSupplierInfo", ReplyAction="http://tempuri.org/IMasterDataService/InsertOrUpdateSupplierInfoResponse")]
        System.Threading.Tasks.Task<bool> InsertOrUpdateSupplierInfoAsync(BussinessSolution.BS_MasterDataService.SupplierInfo supplierInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterDataService/GetProductInfo", ReplyAction="http://tempuri.org/IMasterDataService/GetProductInfoResponse")]
        BussinessSolution.BS_MasterDataService.ProductInfo[] GetProductInfo(BussinessSolution.BS_MasterDataService.PagerInfo pagerInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterDataService/GetProductInfo", ReplyAction="http://tempuri.org/IMasterDataService/GetProductInfoResponse")]
        System.Threading.Tasks.Task<BussinessSolution.BS_MasterDataService.ProductInfo[]> GetProductInfoAsync(BussinessSolution.BS_MasterDataService.PagerInfo pagerInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterDataService/InsertOrUpdateProductInfo", ReplyAction="http://tempuri.org/IMasterDataService/InsertOrUpdateProductInfoResponse")]
        bool InsertOrUpdateProductInfo(BussinessSolution.BS_MasterDataService.ProductInfo productInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterDataService/InsertOrUpdateProductInfo", ReplyAction="http://tempuri.org/IMasterDataService/InsertOrUpdateProductInfoResponse")]
        System.Threading.Tasks.Task<bool> InsertOrUpdateProductInfoAsync(BussinessSolution.BS_MasterDataService.ProductInfo productInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterDataService/GetCategoryInfo", ReplyAction="http://tempuri.org/IMasterDataService/GetCategoryInfoResponse")]
        BussinessSolution.BS_MasterDataService.CategoryInfo[] GetCategoryInfo(BussinessSolution.BS_MasterDataService.PagerInfo pagerInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterDataService/GetCategoryInfo", ReplyAction="http://tempuri.org/IMasterDataService/GetCategoryInfoResponse")]
        System.Threading.Tasks.Task<BussinessSolution.BS_MasterDataService.CategoryInfo[]> GetCategoryInfoAsync(BussinessSolution.BS_MasterDataService.PagerInfo pagerInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterDataService/GetGroupCategoryInfo", ReplyAction="http://tempuri.org/IMasterDataService/GetGroupCategoryInfoResponse")]
        BussinessSolution.BS_MasterDataService.CategoryInfo[] GetGroupCategoryInfo(BussinessSolution.BS_MasterDataService.PagerInfo pagerInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterDataService/GetGroupCategoryInfo", ReplyAction="http://tempuri.org/IMasterDataService/GetGroupCategoryInfoResponse")]
        System.Threading.Tasks.Task<BussinessSolution.BS_MasterDataService.CategoryInfo[]> GetGroupCategoryInfoAsync(BussinessSolution.BS_MasterDataService.PagerInfo pagerInfo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMasterDataServiceChannel : BussinessSolution.BS_MasterDataService.IMasterDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MasterDataServiceClient : System.ServiceModel.ClientBase<BussinessSolution.BS_MasterDataService.IMasterDataService>, BussinessSolution.BS_MasterDataService.IMasterDataService {
        
        public MasterDataServiceClient() {
        }
        
        public MasterDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MasterDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MasterDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MasterDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BussinessSolution.BS_MasterDataService.SupplierInfo[] GetSupplierInfo(BussinessSolution.BS_MasterDataService.PagerInfo pagerInfo) {
            return base.Channel.GetSupplierInfo(pagerInfo);
        }
        
        public System.Threading.Tasks.Task<BussinessSolution.BS_MasterDataService.SupplierInfo[]> GetSupplierInfoAsync(BussinessSolution.BS_MasterDataService.PagerInfo pagerInfo) {
            return base.Channel.GetSupplierInfoAsync(pagerInfo);
        }
        
        public bool InsertOrUpdateSupplierInfo(BussinessSolution.BS_MasterDataService.SupplierInfo supplierInfo) {
            return base.Channel.InsertOrUpdateSupplierInfo(supplierInfo);
        }
        
        public System.Threading.Tasks.Task<bool> InsertOrUpdateSupplierInfoAsync(BussinessSolution.BS_MasterDataService.SupplierInfo supplierInfo) {
            return base.Channel.InsertOrUpdateSupplierInfoAsync(supplierInfo);
        }
        
        public BussinessSolution.BS_MasterDataService.ProductInfo[] GetProductInfo(BussinessSolution.BS_MasterDataService.PagerInfo pagerInfo) {
            return base.Channel.GetProductInfo(pagerInfo);
        }
        
        public System.Threading.Tasks.Task<BussinessSolution.BS_MasterDataService.ProductInfo[]> GetProductInfoAsync(BussinessSolution.BS_MasterDataService.PagerInfo pagerInfo) {
            return base.Channel.GetProductInfoAsync(pagerInfo);
        }
        
        public bool InsertOrUpdateProductInfo(BussinessSolution.BS_MasterDataService.ProductInfo productInfo) {
            return base.Channel.InsertOrUpdateProductInfo(productInfo);
        }
        
        public System.Threading.Tasks.Task<bool> InsertOrUpdateProductInfoAsync(BussinessSolution.BS_MasterDataService.ProductInfo productInfo) {
            return base.Channel.InsertOrUpdateProductInfoAsync(productInfo);
        }
        
        public BussinessSolution.BS_MasterDataService.CategoryInfo[] GetCategoryInfo(BussinessSolution.BS_MasterDataService.PagerInfo pagerInfo) {
            return base.Channel.GetCategoryInfo(pagerInfo);
        }
        
        public System.Threading.Tasks.Task<BussinessSolution.BS_MasterDataService.CategoryInfo[]> GetCategoryInfoAsync(BussinessSolution.BS_MasterDataService.PagerInfo pagerInfo) {
            return base.Channel.GetCategoryInfoAsync(pagerInfo);
        }
        
        public BussinessSolution.BS_MasterDataService.CategoryInfo[] GetGroupCategoryInfo(BussinessSolution.BS_MasterDataService.PagerInfo pagerInfo) {
            return base.Channel.GetGroupCategoryInfo(pagerInfo);
        }
        
        public System.Threading.Tasks.Task<BussinessSolution.BS_MasterDataService.CategoryInfo[]> GetGroupCategoryInfoAsync(BussinessSolution.BS_MasterDataService.PagerInfo pagerInfo) {
            return base.Channel.GetGroupCategoryInfoAsync(pagerInfo);
        }
    }
}
